/* The following code was generated by JFlex 1.3.5 on 13/09/2020 13:33 */

  
/* --------------------------Usercode Section------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 13/09/2020 13:33 from the specification file
 * <tt>file:/home/avilapm/Documents/OBS/Compiladores/Semana_6/SIMPLES/flex/simples.flex</tt>
 */
class SimplesLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  3,  0,  4,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9,  0,  0,  0,  0,  0,  0,  0, 17, 18,  8, 12,  0, 13,  5,  7, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 11, 21, 22, 23,  0, 
     0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 19,  0, 20,  0,  6, 
     0, 28, 10, 26, 14, 24, 35, 32, 10, 15, 10, 10, 29, 33, 34, 31, 
    30, 38, 27, 25, 36, 37, 16, 10, 10, 10, 10,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    39,    78,   117,    39,   156,   195,    39,    39,    39, 
       39,   234,   273,    39,    39,    39,    39,   312,    39,    39, 
      351,   390,   429,   468,   507,   546,   585,   624,   663,   702, 
      741,   780,   156,   819,    39,   858,   897,   936,   975,  1014, 
     1053,  1092,   156,  1131,  1170,  1209,  1248,   663,  1287,   156, 
     1326,  1365,  1404,  1443,  1482,  1521,   156,  1560,  1599,  1638, 
     1677,   156,  1716,  1755,  1794,  1833,  1872,  1911,  1950,  1989, 
     2028,   156,  2067,  2106,   156,  2145,  2184,  2223,   156,  2262, 
     2301,  2340,  2379,   156,  2418,   156,  2457,   156,  2496,   156, 
     2535,  2574,   156,  2613,  2652,  2691,  2730,  2769,  2808,  2847, 
      156,   156,  2886,  2925,  2964,   156,  3003,   156,   156,  3042, 
     3081,  3120,   156,  3159,   156
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\2\5\1\2\1\6\1\7\1\10"+
    "\1\5\1\6\1\11\1\12\1\13\1\14\1\15\1\6"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\2\6\1\27\1\30\1\31\1\32\2\6\1\33"+
    "\1\34\3\6\50\0\1\3\3\0\1\35\44\0\1\5"+
    "\44\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\17\6\7\0\1\36\1\37\37\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\1\6\1\40\1\6\7\0"+
    "\1\41\16\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\12\6\1\42\4\6\15\0\1\43"+
    "\32\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\1\6\1\44\10\6\1\45\4\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\1\46"+
    "\16\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\14\6\1\47\2\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\3\6\7\0\1\50\16\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\3\6\1\51\1\52\12\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\3\6\7\0\15\6\1\53"+
    "\1\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\4\6\1\54\12\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\1\6\1\55\1\6\7\0"+
    "\4\6\1\56\1\57\11\6\1\0\1\60\46\0\1\36"+
    "\7\0\2\36\3\0\3\36\7\0\17\36\7\37\1\0"+
    "\1\61\36\37\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\2\6\1\62\7\0\17\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\1\6\1\63\1\6\7\0"+
    "\14\6\1\64\2\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\2\6\1\65\14\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\14\6\1\66\1\6\1\67\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\12\6\1\70\4\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\1\71\16\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\1\6\1\72\1\6\7\0\17\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\7\6\1\73\7\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\1\6\1\74\1\6\1\75"+
    "\13\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\7\6\1\76\7\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\3\6\7\0\11\6\1\77"+
    "\5\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\2\6\1\100\14\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\3\6\7\0\15\6\1\101"+
    "\1\6\7\0\1\5\40\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\2\6\1\102\14\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\1\103\16\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\3\6\1\104\13\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\4\6"+
    "\1\105\12\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\15\6\1\106\1\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\4\6"+
    "\1\107\12\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\4\6\1\110\12\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\10\6"+
    "\1\111\6\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\1\6\1\112\15\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\4\6"+
    "\1\113\12\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\1\114\1\115\4\6\1\116\10\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\117\12\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\14\6\1\120\2\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\1\6"+
    "\1\121\1\6\7\0\17\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\1\6\1\122\1\6\7\0\17\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\1\123\16\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\7\6\1\124\7\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\4\6\1\125\12\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\7\6\1\126\7\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\3\6\1\127\13\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\7\6\1\130\7\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\12\6\1\131\4\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\1\132\16\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\4\6"+
    "\1\133\12\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\15\6\1\134\1\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\3\6\7\0\7\6"+
    "\1\135\7\6\1\0\1\6\4\0\1\6\3\0\1\6"+
    "\3\0\3\6\7\0\3\6\1\136\13\6\1\0\1\6"+
    "\4\0\1\6\3\0\1\6\3\0\2\6\1\137\7\0"+
    "\17\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\12\6\1\140\4\6\1\0\1\6\4\0"+
    "\1\6\3\0\1\6\3\0\3\6\7\0\4\6\1\141"+
    "\12\6\1\0\1\6\4\0\1\6\3\0\1\6\3\0"+
    "\3\6\7\0\16\6\1\142\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\3\6\1\143\13\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\144\12\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\7\6\1\145\7\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\146\12\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\14\6\1\147\2\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\11\6\1\150\5\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\15\6\1\151\1\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\152\12\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\12\6\1\153\4\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\7\6\1\154\7\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\4\6\1\155\12\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\4\6\1\156\12\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\14\6\1\157\2\6"+
    "\1\0\1\6\4\0\1\6\3\0\1\6\3\0\3\6"+
    "\7\0\12\6\1\160\4\6\1\0\1\6\4\0\1\6"+
    "\3\0\1\6\3\0\3\6\7\0\1\161\16\6\1\0"+
    "\1\6\4\0\1\6\3\0\1\6\3\0\3\6\7\0"+
    "\14\6\1\162\2\6\1\0\1\6\4\0\1\6\3\0"+
    "\1\6\3\0\3\6\7\0\7\6\1\163\7\6";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  9,  1,  1,  9,  9,  9,  9,  1,  1,  9,  9,  9, 
     9,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  0,  1, 
     1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  SimplesLexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  SimplesLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3198];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 112: 
          {   return symbol(sym.DECLFLOAT); }
        case 116: break;
        case 108: 
          {   return symbol(sym.PROGRAM);   }
        case 117: break;
        case 107: 
          {   return symbol(sym.ENQUANTO);  }
        case 118: break;
        case 105: 
          {   return symbol(sym.FIMPARA);   }
        case 119: break;
        case 101: 
          {   return symbol(sym.WRITELINE); }
        case 120: break;
        case 20: 
          {   return symbol(sym.E);         }
        case 121: break;
        case 19: 
          {   return symbol(sym.GREATER);   }
        case 122: break;
        case 18: 
          {   return symbol(sym.EQUALS);    }
        case 123: break;
        case 17: 
          {   return symbol(sym.LESS);      }
        case 124: break;
        case 16: 
          {   return symbol(sym.RBRCKT);    }
        case 125: break;
        case 15: 
          {   return symbol(sym.LBRCKT);    }
        case 126: break;
        case 14: 
          {   return symbol(sym.RPAREN);    }
        case 127: break;
        case 13: 
          {   return symbol(sym.LPAREN);    }
        case 128: break;
        case 7: 
          {   return symbol(sym.TIMES);     }
        case 129: break;
        case 8: 
          {   return symbol(sym.SEMI);      }
        case 130: break;
        case 9: 
          {   return symbol(sym.PLUS);      }
        case 131: break;
        case 10: 
          {   return symbol(sym.MINUS);     }
        case 132: break;
        case 32: 
          {   return symbol(sym.DE);        }
        case 133: break;
        case 34: 
          {   return symbol(sym.ATTRIB);    }
        case 134: break;
        case 37: 
          {   return symbol(sym.IFF);       }
        case 135: break;
        case 42: 
          {   return symbol(sym.OU);        }
        case 136: break;
        case 49: 
          {   return symbol(sym.DIVIDE);    }
        case 137: break;
        case 56: 
          {   return symbol(sym.ATE);       }
        case 138: break;
        case 62: 
          {   return symbol(sym.ENDPRG);    }
        case 139: break;
        case 71: 
          {   return symbol(sym.READLINE);  }
        case 140: break;
        case 74: 
          {   return symbol(sym.PARA);      }
        case 141: break;
        case 78: 
          {   return symbol(sym.FACA);      }
        case 142: break;
        case 83: 
          {   return symbol(sym.THENN);     }
        case 143: break;
        case 85: 
          {   return symbol(sym.ELSEE);     }
        case 144: break;
        case 87: 
          {   return symbol(sym.PASSO);     }
        case 145: break;
        case 89: 
          {   return symbol(sym.ENDELSE);   }
        case 146: break;
        case 92: 
          {   return symbol(sym.STARTPRG);  }
        case 147: break;
        case 100: 
          {   return symbol(sym.DECLINT);   }
        case 148: break;
        case 29: 
          {  /* just skip what was found, do nothing */  }
        case 149: break;
        case 3: 
        case 4: 
          {  /* just skip what was found, do nothing */  }
        case 150: break;
        case 5: 
        case 11: 
        case 12: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 31: 
        case 33: 
        case 35: 
        case 36: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 72: 
        case 73: 
        case 75: 
        case 76: 
        case 77: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 86: 
        case 88: 
        case 90: 
        case 91: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
        case 98: 
        case 99: 
        case 102: 
        case 103: 
        case 104: 
        case 106: 
        case 109: 
        case 110: 
        case 111: 
        case 113: 
          {  return symbol(sym.ID, yytext()); }
        case 151: break;
        case 114: 
          {   return symbol(sym.FIMENQUANTO); }
        case 152: break;
        case 61: 
          {   return symbol(sym.NAO);        }
        case 153: break;
        case 2: 
          {  return symbol(sym.INTT,yytext());  }
        case 154: break;
        case 1: 
        case 6: 
          {  System.err.println("Error: Caracter Ilegal <"+yytext()+"> na linha: " + yyline);  }
        case 155: break;
        case 47: 
          {  return symbol(sym.FLOATT, yytext());  }
        case 156: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
